googollee/go-socket.io

- caller.go
This is a fix to https://github.com/googollee/go-socket.io/issues/51
> fix the panic when client side emits nil data

- adapter.go
- handler.go
- server.go
This fixes the issue I've raised #49 
I'm currently using this successfully in a project and both broadcast and emit are working ok.
> Removed wrapping of arguments to allow arrays to be sent in broadcast (Issue 49)

- server.go
this is the simple wrapper for https://github.com/googollee/go-engine.io/pull/18
> added feature to set max connection

- caller.go
> Move argument check so that too many arguments does not panic.

- .travis.yml
- caller.go
- server.go
refs the PR googollee/go-engine.io#31
> added Count() and GetMaxConnections() to view connected count in session

- adapter.go
> add mutex to broadcast type to fix race condition

- README.md
- example/asset/index.html
- example/main.go
- handler.go
- handler_test.go
* See documentation: http://socket.io/docs/#sending-and-getting-data-(acknowledgements)
* In golang implementation of socket.io used return value instead of callback argument like in documentation.
> Added information about acknowledgements usage / Fixed processing of client packet with ACK type

- handler.go
Read/write on socketHandler.acks map is not protected by any locks.
socketHandler.onAck() reads it, while socketHandler.Emit() writes to it.
These two operations could very well be happening at the same time so
guard it with a lock.
```
WARNING: DATA RACE
Read by goroutine 31:
runtime.mapaccess2_fast64()
/home/nazri/go/src/runtime/hashmap_fast.go:137 +0x0
github.com/googollee/go-socket%2eio.(*socketHandler).onAck()
/home/nazri/gocode/src/github.com/googollee/go-socket.io/handler.go:184 +0x98
github.com/googollee/go-socket%2eio.(*socketHandler).onPacket()
/home/nazri/gocode/src/github.com/googollee/go-socket.io/handler.go:139 +0xaf1
github.com/googollee/go-socket%2eio.(*socket).loop()
/home/nazri/gocode/src/github.com/googollee/go-socket.io/socket.go:135 +0x4ab …
```
> Fix racy read/write on socketHandler.acks

- adapter.go
- handler_test.go
- server.go
Added the function of counting the number of sockets in a room
> add LenRoom method

- client.go
- server.go
- websocket.go
Moved import statements from code.google.com to golang.org
> fixed missing import statements ( moved repositories )

- namespace.go
Just received an error:
```fatal error: concurrent map writes
goroutine 64 [running]:
runtime.throw(0xb3f919, 0x15)
/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0xc420629da8 sp=0xc420629d88 pc=0x42b2d1
runtime.mapdelete_fast64(0xa5e680, 0xc420291950, 0x36b)
/usr/local/go/src/runtime/hashmap_fast.go:843 +0x20f fp=0xc420629de8 sp=0xc420629da8 pc=0x40d76f
github.com/tensor146/go-socket%2eio.(*namespaceConn).dispatch(0xc420291980, 0x3, 0x0, 0x0, 0x36b, 0x1)
/home/mypath/golang/src/github.com/tensor146/go-socket.io/namespace.go:153 +0xa4 fp=0xc420629e48 sp=0xc420629de8 pc=0x99bbf4
github.com/tensor146/go-socket%2eio.(*conn).serveRead(0xc4201b0af0)
/home/mypath/golang/src/github.com/tensor146/go-socket.io/conn.go:211 +0x209 fp=0xc420629fd8 sp=0xc420629e48 pc=0x999e89
runtime.goexit() …
```
> Added handling for concurrent concurrent map writes ("acks" map)

- README.md
修复`Readme`文件中`BroadcastTo`函数的错误
--------
Fix `Readme` file `BroadcastTo` function error
> Fix Readme file BroadcastTo function error

- README.md
I noticed your readme.md is outdated.
Keep up the good work!
> Fixing README.md with working example

- conn.go
This is a WIP branch so the progress and work can be shared among more people.
> WIP: Deadlock on multiple Emit's

- example/default-server/main.go
- example/gin-gonic/main.go
I added new example by go-socket.io and gin-gonic 
Resolved by issue https://github.com/googollee/go-socket.io/issues/261
> ADD: new example with gin-gonic web framework

- README.md
I added notice about base supported version Golang
> UPDATE: readme.md

- conn.go
> BUG#265: not given onDisconnect handler

- README.md
- conn.go
- example/default-server/main.go
- example/gin-gonic/main.go
- namespace.go
- namespace_test.go
- server.go
> ADD: change signature methods in docs, test, examples

- conn.go
- namespace.go
- server.go
#235 Add connection info in OnError callback
> Add connection info in OnError callback

- broadcast.go
- example/emit/main.go
- namespace.go
- server.go
I added new branch - "dev" to new features because we will have to guarantee stable library
> ADD: emit method by issue #132

- parser/decoder.go
This should fix the issues described by a reply in #301
My bad on that one.
> Fix unexpected EOF on large payloads (my bad, sorry!)

- _example/gf/main.go
I added new example by go-socket.io and GF(GoFrame)
> ADD: new example with gf web framework

- engineio/manager.go
- engineio/server.go
- server.go
Requires this merge in go-engine.io: https://github.com/googollee/go-engine.io/pull/93 (and subsequent bump in go.mod)
> Feature: Add method for counting connected clients

- .deepsource.toml
- engineio/payload/errors_test.go
- engineio/payload/payload.go
- parser/encoder_test.go
Hi :wave: I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/go-socket.io/issues/). This PR fixes a few of them.
- Replaced `t.Sub(time.Now())` with `time.Until`
- Merged variable declaration with assignment
- Fixed unnecessary typecasting on `bytes.Buffer`
- Added .deepsource.toml
> Fix: Code quality issues

- .deepsource.toml
I forgot to update the import path before making the PR #410 
-----
Also, I would like to share the steps to activate the [DeepSource](https://deepsource.io/) analysis on the repo. Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. You can also use it to track test coverage and detect problems in Dockerfile.
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create a `.deepsource.toml` configuration which you can use to configure your analysis settings.
- Activate analysis [here](https://deepsource.io/gh/googollee/go-socket.io/).
Note: The PR #410 merged the `.deepsource.toml` file so you need not create the configuration file but if you want you can modify it any …
> Correction in `import_path` of DeepSource

- redis_broadcast.go
The latest uuid doesn't return an error.
> Revert "Patch fix for 'multiple value' Satori UUID issue (#422)"

- .golangci.yml
- engineio/payload/decoder_test.go
- engineio/payload/encoder_test.go
- engineio/payload/errors.go
- engineio/payload/payload.go
- engineio/payload/payload_test.go
- engineio/payload/util_test.go
- engineio/transport/websocket/wrapper.go
- redis_broadcast.go
by issue https://github.com/googollee/go-socket.io/issues/454
> add: fix lint

- adapter_options.go
- redis_broadcast.go
- server.go
> feat: add redis auth option

- engineio/server.go
- engineio/session/session_id_generator.go
- engineio/session/session_manager.go
- engineio/transport/manager.go
- engineio/transport/manager_test.go
- engineio/transport/transport.go
- namespace_conn.go
* minor changes in comment and engineio serve
> cleanup: minor changes

- connection.go
- server.go
Look up this issue https://github.com/googollee/go-socket.io/issues/510
> fix: session manager leak after client disconnected

- _examples/README.md
edit README
- add Addr variable in init RedisAdapterOptions struct
> fix(examples) : README  add Addr in redisAdapterOptions

- engineio/payload/payload.go
My latest #553 lat a unsuded `fmt`remain, so the master branch code failes compiling
> Remove unused `fmt`

- server.go
errorMessage type assertion should use pointer type
> fix: errorMessage type assertion

- .github/workflows/ci.yaml
- .golangci.yml
- _examples/default-http/main.go
- connection.go
- connection_handlers.go
- engineio/client.go
- engineio/dialer.go
- engineio/packet/decoder_test.go
- engineio/packet/encoder.go
- engineio/packet/encoder_test.go
- engineio/payload/encoder.go
- engineio/payload/payload_test.go
- engineio/server_test.go
- engineio/session/base.go
- engineio/session/session.go
- engineio/transport/polling/connect.go
- engineio/transport/polling/connect_test.go
- engineio/transport/polling/polling_test.go
- engineio/transport/polling/server_test.go
- engineio/transport/websocket/connect_test.go
- engineio/transport/websocket/websocket_test.go
- parser/decoder.go
- parser/encoder.go
- server.go
Handle errors and write to log
> fix: lint errors

- connection_handlers.go
- engineio/transport/polling/connect.go
- engineio/transport/polling/server.go
- server.go
I have been doing a bunch of debugging and these are some fixed logging lines that have helped.
1. Log events and namespaces when not found
2. Log when errors occur before disconnecting
3. Change log messages for different lines in code so they can be located easier
> Fixing some logging

- _examples/README.md
- _examples/client/main.go
- _examples/default-http/main.go
- client.go
- connection_handlers.go
This is a very early implementation of a client, it is not well tested but works for me currently (perhaps better with my other PRs)
I think this would be a good base to build from, so I am sharing now as a means of communicating progress. 
If merged, I think we should also include some docs and a disclaimer that this is still very beta.
Graham
> Attempt at a client

- client.go
General:
- remove debug outpus
- move s -> c maning into inner methods
- ref package and varibale name - `url`
- check empty addr string
jfyi: @grahamjenson
> ref: client file
