googollee/go-socket.io

- session.go
The heartbeat timeout is given by the server, so it you then set the heartbeat timeout on the client to 2/3th of that and the connection timeout on exactly on par with the servers heartbeat timeout, bad things will happen… This should fix issue #40
I fixed this locally a few months ago, but deleted that branch as I don't use the package anymore. So did not test this fix myself as I have no infra for it around me just now. But will ask @zhengying if he can check this one.
> It seems there is a small logic error wit the timers

- handler.go
c.Args can end up a different length from the handler.go's args. This means the client can cause a panic just by not sending a second argument to it's .emit(). Proposed change just populates the args with nils so that the reflect.Zero in callers.go is hit.
edit: accidentally clicked submit. adding more to this comment
> fixing empty emit from client

- server.go
this is the simple wrapper for https://github.com/googollee/go-engine.io/pull/16
> added feature to allow custom connection id generator

- socket.go
See: https://github.com/googollee/go-socket.io/issues/59
The socket.io client requires an echoed connect packet,
which is mising from the current code.
NOTE: I believe navneetk's example from Mar 18 2015 shows
a different issue.
> Fix for issue 59

- parser.go
When sending Binary data, the socket.io client strips the binary
data from the frame and replaces it with a numbered _placeholder.
Once the placeholder frame is ack'ed the client sends another
frame with the binary data.  Without this fix go-socket.io never
acks the placeholder frame and so waits indefinitely for the data
frame.
> fixes #48 close the open chanel before waiting for nextReader

- handler.go
- parser.go
This is a fix for #67.
Fixed the problem that the server would not respond to any other emit once an unknown emit was sent to the server.
If the message was not understood by the server, it would return right away without closing the decoder. This would lead to a hang up at this location: [Problematic Line](https://github.com/googollee/go-engine.io/blob/597faf3df88a01780a5881fafbcbccd9d5c3fab0/server_conn.go#L222)
I also took the liberty of adding a new Close() function to the decoder interface, since the lines were repeated at multiple places in the code.
> fix for #67. It will now close the packet when reading an unknown emit

- parser.go
This PR fixes #88, however it feels like kind of a hack around a deeper problem. Any ideas why decoder.Close() is being called in the first place if decoder is nil?
> Workaround to panic when attempting to close nil decoder

- handler.go
Ok we just tested using this commit on our production and thanks to those changes we have 100% uptime so far. Before socketio would panic every now and then due to nil dereference exception in handler.go; so I suggest this is reopened and merged.
Thanks to @aitjcize for this fix, I just reopened the pull request.
> Fix nil dereference exception in handler.go

- adapter.go
- attachment.go
- example/asset/socket.io.js
- handler.go
- main.go
- namespace.go
- server.go
- socket.go
Correct grammatical errors with the documentation, and change parts where the documentation and argument names will state "message" when it actually means "event".
> Clarify documentation and argument names

- socket.go
Simultaneous calls to Socket.Emit with callback is racy on socket.id:
```
WARNING: DATA RACE
Read by goroutine 101:
github.com/googollee/go-socket%2eio.(*socket).sendId()
/home/nazri/go/src/github.com/googollee/go-socket.io/socket.go:94 +0xac
github.com/googollee/go-socket%2eio.(*socketHandler).Emit()
/home/nazri/go/src/github.com/googollee/go-socket.io/handler.go:72 +0x492
github.com/googollee/go-socket%2eio.(*socket).Emit()
/home/nazri/go/src/github.com/googollee/go-socket.io/socket.go:61 +0x99
...
Previous write by goroutine 98:
github.com/googollee/go-socket%2eio.(*socket).sendId()
/home/nazri/go/src/github.com/googollee/go-socket.io/socket.go:98 +0x15c
github.com/googollee/go-socket%2eio.(*socketHandler).Emit()
/home/nazri/go/src/github.com/googollee/go-socket.io/handler.go:72 +0x492 …
```
> Fix racy read/increment of socket.id for emits with ack

- client.go
- server.go
- session.go
- websocket.go
The websocket library is no longer hosted on code.google.com, so I updated the path. Also, Go 1.10 flagged a truncation error in a line that computes the connection timeout, so that's fixed too.
> Updates import path of websocket library and fixes constant truncation error.

- namespace.go
Server->client event can not be acked because packages contain no package id, because there are no "need ack" flag to write package id writer.
> Server->client event can not be acked

- adapter.go
Add a reading lock for Len() function in order to prevent reading room map during write operations
> Add lock for reading.

- handler.go
- handler_test.go
- parser.go
- parser_test.go
When you create a handler without arguments like this `socket.On ("something", func () {...})`, you will have a lock [here](https://github.com/googollee/go-engine.io/blob/master/server_conn.go#L230), because the handler doesn't get [here](https://github.com/googollee/go-socket.io/blob/master/handler.go#L160) and so the reader is [not closed](https://github.com/googollee/go-socket.io/blob/master/parser.go#L300).
So I moved the Close() method [here](https://github.com/googollee/go-socket.io/blob/master/handler.go#L131). It seems more logical to perform it at that level, if I didn't miss anything.
Thanks.
> Fix problem with closing the reader when the handler 'On' without args

- conn.go
Closes #255
If no `server.OnError` error event is attached this NPE (nil pointer exception) could happen.
> Do not crash on a handler's onError method being undefined

- .gitignore
- broadcast.go
- conn.go
- namespace.go
- server.go
```
// JoinRoom joins given connection to the room
JoinRoom(room string, connection Conn)
// LeaveRoom leaves given connection from the room
LeaveRoom(room string, connection Conn)
// LeaveAllRooms leaves the given connection from all rooms
LeaveAllRooms(connection Conn)
// ClearRoom clears the room
ClearRoom(room string)
// BroadcastToRoom broadcasts given event & args to all the connections in the room
BroadcastToRoom(room, event string, args ...interface{}) 
// RoomLen gives number of connections in the room
RoomLen(room string) int
//  Rooms gives list of all the rooms
Rooms() []string
```
```
Join(room string)
Leave(room string)
LeaveAll()
Rooms() []string
```
> Broadcast & Rooms support added back

- conn.go
These changes are intended to address two related issues:
1. When a client connection simply drops (without sending a disconnect message/packet), the handler registered with `OnDisconnect` is not called.  Instead this case is only caught by `OnError`, with the error message `"websocket: close 1001 (going away)"`.  [As was the case with v1.0](https://github.com/googollee/go-socket.io/blob/039301c93651993bc96b7b00b1c60592a31f5a1f/socket.go#L123-L130), when the socket/connection loop(s) return, a disconnect should be triggered.  In v1.4.2, this is when any of the `conn` send/receive/error loops terminate and `Close` is called.
2. When broadcast and room functions were re-added in https://github.com/googollee/go-socket.io/pull/239, disconnected (or lost as in the first issue) connections …
> conn: On Close, leave all rooms, and call the disconnect handler

- example/gin-cors/main.go
This patch fixes a bug in gin-cors example:
```
example/gin-cors/main.go:57:22: cannot use func literal (type func(error)) as type func(socketio.Conn, error) in argument to server.OnError
```
> Fixes bug in gin-cors example

- go.mod
- go.sum
Establishing a polling connection is incredibly slow with engine.io 1.4.1 but the issue seems to be fixed in the latest tagged version (1.4.2).
For some reason the latest version wasn't referenced in the go.mod file.
Might be related to  #312, maybe the creator of the issue can confirm/deny?
> Update engine.io to latest tagged version 1.4.2

- parser/decoder.go
Ran into the same issue as the guy with #297 but the solution he suggested seemed a bit overkill for me.
Can't we just Close the reader currently set to lastFrame before decoding the already read data to json?
It was closed after decoding to json anyway, doing it before or after shouldn't really matter as all the relevant data is accessible through r.
I could be wrong because I missed something, but the tests don't throw any errors and it seems to be cleaner than the solution suggested in #297 .
> Fix annoying reminder to call Close() on Reader (corresponds with #297)

- conn.go
In my project, i set the context of engineio.Conn at connInitior. Here's the link: [https://github.com/tomruk/oraj/blob/master/api/socket/auth.go#L36](https://github.com/tomruk/oraj/blob/master/api/socket/auth.go#L36)
But when i want to get that context from socketio.Conn, the value is always nil. For example:
```go
IO.OnConnect("/", func(conn socketio.Conn) error {
fmt.Println(conn.Context())
return nil
})
```
It always prints nil. I changed some functionality in conn.go so if i set the engine.io context, it sets the socke.tio context at the very beginning.
> Set context of the engineio.Conn to socketio.Conn

- parser/data.go
- parser/decoder.go
Check if Header.Namespace field has a '?' and if so, slice it to another field Header.Query
This also fixes #361
> Fix #347: slice non-namespace character out of Namespace field

- server.go
1. _example default-http & go-echo failed with "invalid sid"
2. apply the fix, _example run OK
> fix: creating namespace and getting namespace be consistent

- redis_broadcast.go
The UUID package should probably be changed to something else, as the Satori package is dead.  I am proposing this patch fix as I am very thankful for this library, and this recent change broke my websocket server.
> Patch fix for 'multiple value' Satori UUID issue

- engineio/base/util.go
- engineio/base/util_test.go
> Add TimestampFromClock(); add Clock interface for mocking time.Now()

- go.mod
- go.sum
- helpers.go
- redis_broadcast.go
Due to https://github.com/satori/go.uuid is dead and no longer maintains
https://github.com/satori/go.uuid/issues/84
I request to change to https://github.com/gofrs/uuid
> fix uuid.NewV4() in single-value context error by change to use github.com/gofrs/uuid

- engineio/payload/payload.go
Address #552 by just removing `fmt.Println("resume")` it
> Remove fmt.Println("resume") from Payload's Resume

- broadcast.go
```
func (bc *broadcast) Rooms(connection Conn) []string 
```
if connection is nil, the lock will RLock twice and it might deadlock
> fix:RLock twice when broadcast.Rooms(nil)

- _examples/README.md
- adapter_options.go
- redis_broadcast.go
- server.go
Add `DB` option to `RedisAdapterOptions` for specifies the database in `redis.Dial`
> Add DB option to RedisAdapterOptions

- _examples/README.md
- server.go
Fixed the leak, everything is quiet.
First，the services connections not  growing，it's keep consistent with the number of socket connections（1w+ connections  of 1.1 G mem）， 
eg1.
eg2.
Second，the machine fd has down，will not cause fd to spike and cause excessive machine load 
eg1.
> [Fixed] Resoved the sessions leak(connections & mem)

- engineio/payload/data_test.go
- engineio/payload/decoder.go
- engineio/payload/decoder_test.go
- engineio/payload/encoder.go
So this is a horrible problem and I am pretty sure this is not a 100% fix, but does fix some of the problems.
The packet encoding which includes the length of the packet data is incorrect because Javascript.length is not byte length and not Rune length, there is no direct analog in Golang but Javascript length is always less than either of those. Add to that, we must do this encoding/decoding in a stream makes it even harder.
I fixed this in
1. Decode: increasing the limit of the limit reader while reading the packet based on the unicode header we just saw, this means the packet reader will keep reading further
2. Encode: increasing the calculated length by scanning for unicode header bytes and adding to the length based on their byte value.
Both these solution are not 100% because the …
> Fix(ish) for unicode encoding in packet
